function out1 = lin_dyn(x,x_dot,theta,theta_dot)
%LIN_DYN
%    OUT1 = LIN_DYN(X,X_DOT,THETA,THETA_DOT)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    25-Apr-2022 09:42:22

t2 = cos(theta);
t3 = theta_dot.^2;
t5 = x.*2.54530756753206e-3;
t4 = t2.^2;
t6 = t5-5.415141849924458e-4;
out1 = reshape([0.0,t3.*t4.*2.54530756753206e-3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,t2.*4.182877287225114e-1-t2.*t3.*t6.*sin(theta).*2.0,0.0,0.0,0.0,t4.*t6.*theta_dot.*2.0,1.0,-4.0e+1,0.0,0.0,0.0,6.0e+1],[4,5]);
