function f = nonlin_dyn(x,x_dot,theta,theta_dot,u)
%NONLIN_DYN
%    F = NONLIN_DYN(X,X_DOT,THETA,THETA_DOT,U)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    25-Apr-2022 09:42:21

f = [x_dot;sin(theta).*4.182877287225114e-1+theta_dot.^2.*cos(theta).^2.*(x.*2.54530756753206e-3-5.415141849924458e-4);theta_dot;theta_dot.*-4.0e+1];
